- .idea/misc.xml
- src/main/java/entities/Main.java
- src/main/java/entities/User.java
- src/main/java/entities/View.java
- src/main/java/features/Listing.java
- src/main/java/forms/CreateListingForm.java
- src/main/java/forms/Form.java
I have finished the code for creating a listing, as well as the listing class (that you guys can all access).
> Feature 2 creating a listing

- src/main/java/entities/DatabaseInteractor.java
the interface has create, query, update, and delete methods. the interface has a table method, to specify which table it will work on (Listings, Users, Reviews).
i think we will write an interactor for each use case, which will implement the main interface. yeah?
> 12 Create DatabaseInteractor Interface

- src/main/java/features/Listing.java
- src/main/java/forms/CreateListingForm.java
- src/main/java/pages/ListingDetailPage.java
- reworked how ids work for Listing class. implemented an atomic counter from 0
- created ListingDetailPage, dependent upon other code and currentUser for final implementation
thoughts?
> Feature 5: Listing Detail Page

- src/main/java/features/Cart.java
- src/main/java/pages/CartPage.java
Cart is complete and thoroughly documented. The errors are due to the fact Listing hasn't been implemented yet.
//TODO has been written in all places where work is not complete.
CartPage is incomplete but the logic is basically there. It's uncomfortable to finish because it heavily relies on the GUI and we haven't quite figured out how we will be using View and rendering pages. CartPage is also very roughly documented but for now, that should work. Any errors are due to the fact it is not complete and can be safely ignored for now.
> feature 7 cart page

- src/main/java/database/DatabaseInteractor.java
- src/main/java/entities/Main.java
added DatabaseInteractor class
instantiated databaseInteractor and currentUser variables in main()
should databaseInteractor and currentUser in main() be instance attributes of the Main class, or just regular variables in the main() method?
> Add DatabaseInteractor and currentUser

- src/main/java/database/GetUser.java
Fixed the error in GetUser. Thanks for finding it, I think that's the error I was looking for during tutorial.
> Replaced instance of ReviewDatabseController in GetUser

- build.gradle
- src/main/java/database/DatabaseController.java
added opencsv dependency to build.gradle file. to make it work, rebuild the project and restart your intellij
uncommented methods using opencsv in the DatabaseController file
> add opencsv dependency to gradle, uncomment db methods

- .gitignore
- .idea/misc.xml
please look through the files and confirm that we don't have any files we don't want! i think i got them all...
> Remove unwanted .idea files from project

- src/main/java/entities/View.java
I refactored the View so that instead of adding the navBar to each Page then displaying, I figured out in Swing how to add the NavBar and the View separately. As long as you leave 150 pixels blank on top, the navBar should no longer have any effect on your Page layout.
> Refactor view

- src/main/java/UI/CreateListingPage.java
- src/main/java/forms/CreateListingForm.java
- src/main/java/useCase/createListing/ListingCreator.java
- src/main/java/useCase/createListing/ListingInteractor.java
- src/main/java/useCase/createListing/ListingRequestModel.java
Hello all,
I have implemented it such that the submit button creates a form and sends a request and receives a response. 
I have to do two more things,
I need to figure out how to scale the image.
and the form validation works!
> Create listing w db

- src/main/java/UI/CreateListingPage.java
- src/main/java/UI/NavBar.java
- src/main/java/useCase/createListing/ListingInteractor.java
As title states, I have made it so that there is text on successful listing creation and we clear the text box when that happens.
And when the details are bad, we show the following.
and if for whatever reason someone isnt logged in tries to create a listing, they see the following
> Show success or fail text and clear form on successful submission

- src/main/java/useCase/login/LoginInteractor.java
The login page wasn't working when I entered the username of a User that doesn't exist, but I eventually figured out that the databaseController returns Null in that case, so I've refactored for it to work now
> Fixed the loginInteractor so that catches when the User returned is Null

- src/main/java/database/DatabaseController.java
- src/main/java/entities/Listing.java
- src/main/java/entities/User.java
- src/test/java/database/GetAllListingsUnitTests.java
- src/test/java/database/Listings.csv
- src/test/java/database/SerializerUnitTests.java
added tests for getAllListingsUnitTests
> Database controller get all listings tests

- src/main/java/UI/CartPage.java
- src/main/java/entities/Cart.java
- src/test/java/entities/CartUnitTests.java
Fixed minor bug with GetPrice in Cart returning an int. Added Unit tests for all methods of cart. Added comments to CartPage and fixed some comments in Cart.
> Tests and Comments

- src/main/java/UI/CartPage.java
CHanged layout to work properly
> Changed Layout

- src/main/java/UI/CartPage.java
Error that stopped the panel from displaying in small windows fixed.
> FIxed Errors

- src/main/java/database/DatabaseController.java
- src/test/java/database/Listings.csv
- src/test/java/database/Users.csv
- src/test/java/database/getListingByUserUnitTests.java
tests are functional for getting listings by username method
> Get listing by user tests

- src/main/java/UI/ListingListPage.java
- src/main/java/database/DatabaseController.java
- src/test/java/database/CheckUserWithUsernameUnitTests.java
- src/test/java/database/Listings.csv
- src/test/java/database/Users.csv
test when username does not exist and when it does. Passes all tests
> tests pass checking duplicate usernmae

- src/test/java/database/CheckUserWithUsernameUnitTests.java
- src/test/java/database/Listings.csv
- src/test/java/database/Users.csv
added afterall for tests, deleted csv files
> add afterall, delete csvfiles

- src/test/java/database/Listings.csv
- src/test/java/database/Users.csv
- src/test/java/database/getListingByUserUnitTests.java
remove csv files, add after all to getlistingbyuser tests
> add-after-all, remove csv files

- src/test/java/database/CreateListingUnitTests.java
- src/test/java/database/Listings.csv
- src/test/java/database/Users.csv
added afterall to createlisting tests, remove csv files
> remove csv files, update afterall, beforeall

- src/test/java/database/CheckUserWithEmailUnitTests.java
- src/test/java/useCase/Register/RegisterResponseModelUnitTests.java
wrote unit tests for DatabaseController.checkUserWithEmail()
> checkUserWithEmail unit tests

- src/main/java/database/CheckoutDatabaseGateway.java
- src/main/java/database/DatabaseController.java
- src/test/java/database/AddReviewUnitTests.java
- src/test/java/database/RemoveListingUnitTests.java
- src/test/java/useCase/Register/RegisterResponseModelUnitTests.java
fixed DatabaseController.addReview() method
wrote tests
> DatabaseController addReview() and Tests

- src/main/java/database/DatabaseController.java
- src/test/java/database/RemoveFromCartByIDUnitTests.java
- src/test/java/useCase/Register/RegisterResponseModelUnitTests.java
wrote DatabaseController.removeFromCartById()
wrote tests
> DatabaseController Remove Listing From Cart Tests

- src/main/java/database/DatabaseController.java
- src/test/java/database/CheckoutRemoveListingsUnitTests.java
- src/test/java/useCase/Register/RegisterResponseModelUnitTests.java
Tested DatabaseController.checkoutRemoveListings
> Checkout remove listings tests

- src/test/java/database/AddReviewUnitTests.java
Refactor to use User.getREVIEWS() instead of User.getReviews
> Refactor to use User.getREVIEWS() instead of User.getReviews

- src/test/java/database/CheckoutRemoveListingsUnitTests.java
> fix exceptions

- src/main/java/UI/CheckoutPage.java
- src/main/java/UI/ListingListPage.java
- src/main/java/forms/CheckoutForm.java
- src/main/java/forms/Form.java
- src/main/java/useCase/checkout/CheckoutInteractor.java
- src/main/java/useCase/checkout/CheckoutResponseModel.java
fixed ListingListPage to be able to display searched listings 
fixed checkout to remove items from database
> Checkout database

- src/main/java/UI/CheckoutPage.java
- src/main/java/entities/data/Listings.csv
- src/main/java/entities/data/Users.csv
cleared csvs in data so it's empty to start
> Clear csvs
